# @format

version: '3'

services:
  # mongo:
  #   image: mongo:4.0
  #   restart: on-failure
  #   container_name: mongo-20hcb1
  nginx:
    restart: on-failure
    image: nginx:stable-alpine
    container_name: nginx-20hcb1
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-network
    ports:
      - 80:80
  api:
    restart: on-failure
    container_name: api-20hcb1
    build: .
    networks:
      api-network:
        aliases:
          - api-20hcb1
    volumes:
      - .:/api
    command: npm run dev

networks:
    api-network: